Repository ubco-video-game-development-club/rpg, pull requests merged in 2021-09, with the labels that each got.

#34 Alignment
  Assets/Scenes/Main.unity
  Assets/Scripts/Game/Core/PropertyName.cs
  Assets/Scripts/Game/GameManager.cs
  Assets/Scripts/Game/Leveling/AlignmentSystem.cs
  Assets/Scripts/Game/Leveling/AlignmentSystem.cs.meta
  Assets/Scripts/Game/UI/AlignmentGraph.cs
  Assets/Scripts/Game/UI/AlignmentGraph.cs.meta
  Assets/Sprites/InnerHealthBar.png
  Assets/Sprites/InnerHealthBar.png.meta
  Assets/Sprites/ToDoList.png
  Assets/Sprites/ToDoList.png.meta
  Assets/Sprites/noteBook.png
  Assets/Sprites/noteBook.png.meta
Labels: Systems, Feature

#38 Enemy AI Behaviours
  Assets/Data/Behaviour Trees/Test Tree.asset
  Assets/Data/Behaviour Trees/TestBehaviourTree.asset
  Assets/Data/Behaviour Trees/TestBehaviourTree.asset.meta
  Assets/Scenes/Main.unity
  Assets/Scripts/Editor/BehaviourTreeInspector.cs
  Assets/Scripts/Editor/BehaviourTreeWindow.cs
  Assets/Scripts/Tools/Behaviour Tree/Agent.cs
  Assets/Scripts/Tools/Behaviour Tree/AttackNode.cs
  Assets/Scripts/Tools/Behaviour Tree/AttackNode.cs.meta
  Assets/Scripts/Tools/Behaviour Tree/BehaviourTree.cs
  Assets/Scripts/Tools/Behaviour Tree/BehaviourTreeNodeCreator.cs
  Assets/Scripts/Tools/Behaviour Tree/GetPlayerNode.cs
  Assets/Scripts/Tools/Behaviour Tree/GetPlayerNode.cs.meta
  Assets/Scripts/Tools/Behaviour Tree/GetPriorityTargetNode.cs
  Assets/Scripts/Tools/Behaviour Tree/GetPriorityTargetNode.cs.meta
  Assets/Scripts/Tools/Behaviour Tree/IBehaviourTreeNode.cs
  Assets/Scripts/Tools/Behaviour Tree/IsNullNode.cs
  Assets/Scripts/Tools/Behaviour Tree/IsNullNode.cs.meta
  Assets/Scripts/Tools/Behaviour Tree/MoveNode.cs
  Assets/Scripts/Tools/Behaviour Tree/MoveNode.cs.meta
  Assets/Scripts/Tools/Behaviour Tree/MoveRandomNode.cs
  Assets/Scripts/Tools/Behaviour Tree/MoveRandomNode.cs.meta
  Assets/Scripts/Tools/Behaviour Tree/NotNode.cs
  Assets/Scripts/Tools/Behaviour Tree/NotNode.cs.meta
  Assets/Scripts/Tools/Behaviour Tree/SelectorNode.cs
  Assets/Scripts/Tools/Behaviour Tree/SequenceNode.cs
  Assets/Scripts/Tools/Behaviour Tree/TestMoverNode.cs
  Assets/Scripts/Utils/VariableProperty.cs
Labels: Systems, Feature

#43 Fix NPC interaction
  Assets/Scenes/Main.unity
Labels: Systems, Bug

#47 Integrate alignment mods into dialogue nodes
  Assets/Data/Dialogue Graphs/TestNPCDialogue.asset
  Assets/Scripts/Editor/DialogueGraphInspector.cs
  Assets/Scripts/Game/UI/DialogueSystem.cs
  Assets/Scripts/Tools/Dialogue Graph/DialogueGraphNode.cs
Labels: Systems, Tools, Feature

#52 Update assets and tilemap to new aspect ratio
  Assets/Scenes/Main.unity
  Assets/Sprites/Dirt.png
  Assets/Sprites/Dirt.png.meta
  Assets/Sprites/Grass.png
  Assets/Sprites/Grass.png.meta
  Assets/Sprites/goof-duck.png.meta
  Assets/Sprites/goof.png.meta
Labels: Content

#53 Delete smiley image
  Assets/Sprites/Smiley.png
Labels: Content, Feature

#69 Implement UniqueID system
  Assets/Scripts/Game/Core/Entity.cs
  Assets/Scripts/Game/Core/UniqueID.cs
  Assets/Scripts/Game/Core/UniqueID.cs.meta
Labels: Systems, Feature
